Jessica/ping
cuappdev/pear-django-backend pull request #115
Opened 2022-04-20 22:11 UTC by jzs27

## Overview

Changed url for pear-ping from /api/me/ to /api/me/ping/

## Changes Made

- Added PingView
- Added PingPersonController

## Test Coverage

Manually Using Postman

</details>

2022-04-21 00:33 UTC, alanna-zhou requested changes
nice work! 

it's super important to have trailing slashes, or else the request will sometimes fail
also, could you update the PR title to be something with an action verb like "Update ping endpoint" ?

2022-04-21 00:33 UTC, alanna-zhou commented on src/api/urls.py
> +    path("me/ping", PingView.as_view(), name="ping"),
should always have trailing slash

2022-04-21 01:37 UTC, chalo2000 requested changes
The code I saw didn't reflect this PR's title or body. Can you change it up so I have a better idea of what you're trying to accomplish here?

2022-10-06 03:32 UTC, chalo2000 approved these changes

2022-10-12 20:46 UTC, merged